### ISSUE TITLE
On ubuntu 20 and 18. Unable to create uploads folder automatically. 

### ISSUE THREAD

**Issue by fais3000** [rez0n/docker-nodebb#61]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

**Error occurred during upgrade: TypeError: Cannot read property 'uploads' of undefined.**

docker-compose was unable to create the uploads folder automatically. This caused nodebb container not to build the assets properly. 

```mkdir uploads ``` 

in the root folder fixed the issue.

PS. On MacOS it seemed to setup things file, this makes me believe it is a permissions issue. 

FYI. my docker-compose file also setups a mongodb instance with a username and password for nodebb database.

[Details of the setup here 
](https://craftypixels.com/nodebb-docker/)

**Comment by rez0n** [comment]
Take a look here: [#8560](https://github.com/NodeBB/NodeBB/issues/8560)
It is a (bug?) in the stable release of NodeBB 1.14.x, which is fixed in 1.15.x (upgrade process crashing on low memory instances)
Uploads folder supplied in the NodeBB package and processed by [entrypoint.sh#L28](https://github.com/rez0n/docker-nodebb/blob/master/entrypoint.sh#L28)

Thanks for your investigation.
